# Generated by Django 3.1.6 on 2021-02-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='userid',
        ),
    ]
